# Generated by Django 2.2.1 on 2019-09-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCNN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
