# Generated by Django 2.2.1 on 2019-09-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCNN', '0002_user_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookie',
        ),
    ]
