# Generated by Django 2.2.1 on 2019-09-04 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebCNN', '0003_remove_user_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.ImageField(default='', upload_to='origin/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WebCNN.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
